### ISSUE TITLE
Auto-importing uno.css does not correctly generate new styles on hot-reload

### ISSUE THREAD

**Issue by yellowsink** [AllanChain/astro-uno#2]
For example, if I switch out `text-white` on a div to, say, `text-[#f9c]` (chosen because it wont exist elsewhere in my site), then it doesn't hot-reload properly.

If I `import "uno.css"` in my layout FrontMatter, then doing this now correctly hot reloads the style onto the page.

This is pretty much the same issue tailwind and windi have where new styles cannot be generated until server restart, except here it occurs only when relying on auto import of uno.css.

**Comment by AllanChain** [comment]
I can't reproduce this. Which version of Astro are you using?

**Comment by yellowsink** [comment]
1.0.0-rc7
i will attempt to reproduce in a clean project.

**Comment by yellowsink** [comment]
intriguing; doesnt happen in a clean project.
i've probably set something up wrong then.
