### ISSUE TITLE
Cannot find module 'uno.css-hmr-fix'

### ISSUE THREAD

**Issue by Nauxscript** [AllanChain/astro-uno#4]
Hi, today I got the error below when i use astro-uno:

```
Error: Cannot find module 'uno.css-hmr-fix' imported from 'astro:scripts/page-ssr.js'
```

and i check the source notice that in your code:

```
 // Apply the plugin and alias
  updateConfig({
    vite: {
      resolve: {
        alias: {
          'unocss-hmr-fix': 'uno.css'
        }
      },
      plugins: [
        unocssPlugins
      ]
    }
  })

  if (options?.astro?.autoImport ?? false) {
    // Auto import UnoCSS
    injectScript('page-ssr', "import 'uno.css-hmr-fix';")
  }
```

if the output unocss file alias is 'unocss-hmr-fix', maybe its below code should change to `injectScript('page-ssr', "import 'unocss-hmr-fix';")` ? 

I try to do it, and it did work and error gone.

**Comment by AllanChain** [comment]
Yes, you're right. I think it's a typo. And I'll fix it later today.
